version: '3.7'

services:
  node-app:
    build: ./node-app
    ports:
      - "3000:3000"
    volumes:
      - ./node-app:/usr/src/app
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nodedb
    ports:
      - "3306:3306"

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node-app
